# Use root/example as user/password credentials
version: '3'

networks:
  nova-net:
    driver: bridge

volumes:
  mysql-vol:
  
services:

  db:
    image: mysql
    container_name: mysql_tasks
    restart: always
    networks:
     - nova-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-vol:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api-web:
    depends_on:
      - db
    build: ./backend
    image: api-web-express:2
    restart: always
    ports:
      - "3333:3333"
    networks:
     - nova-net
    





