apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: vnmoliveira/vnmoliveira/web-api-node
        ports:
        - containerPort: 3333

---

apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: web-api
  ports:
  - port: 3333
  type:
    NodePort

